### ISSUE TITLE
No Lint Results

### ISSUE THREAD

**Issue by msp1kpj** [KamasamaK/vscode-cflint#12]
Hello,

I have just update to v0.3.2 and it does not appear to be executing the CFlint jar. I have check the config paths and that I am using the Cflint v1.4.1. When watching the task manager I am not seeing the JAR being executed on a file open or a file save. I am not sure what more information I can give to help troubleshoot. I have 7 other co-workers that have report the same issues. 

Let me know what information it any that I can give that might help resolve this issue.

VS Code v1.30.2(user setup)
OS: Windows 10

**Comment by KamasamaK** [comment]
This is a side effect of the CFML extension crashing during its initial scan. The scan must open a lot of files, but this will kill your system if CFLint is run on all of them which will happen if you have `cflint.runModes.onOpen` set to `true` which is the default. To bypass this issue, the CFML extension disables CFLint during its scan. If the scan crashes, the setting is never reverted.

So the fix is just to check that your `cflint.enabled` is not set to `false`.

**Comment by bardware** [comment]
> So the fix is just to check that your `cflint.enabled` is not set to `false`

Where to check?
I modified my `settings.json` to
```
   "cflint.runModes": {
        "onOpen": false,
        "onSave": true,
        "onChange": false
    },
    "cflint.enabled":true,
```

Closed all .cfm and .cfc files. Closed code. Started code again. Opened a file. Saved it - still no CFLint output :(

**Comment by KamasamaK** [comment]
@bardware It's best to check at the lowest level first, which is workspace (folder) settings.

**Comment by bardware** [comment]
> first, which is workspace (folder) settings

Didn't look there. It said `"cflint.enabled": false`. No idea how this setting got there.
