### ISSUE TITLE
Will it use root `.cflintrc`

### ISSUE THREAD

**Issue by lmajano** [KamasamaK/vscode-cflint#5]
If you have a `.cflintrc` in the root of your project, will it use it?

**Comment by KamasamaK** [comment]
@lmajano It will use the first `.cflintrc` file it finds traveling up the file hierarchy from the file being linted. If it does not encounter one before reaching the root, then it will use that one.

**Comment by lmajano** [comment]
Thanks

**Comment by lmajano** [comment]
I will reopen this because I find it impossible to work with our cflint file.  
https://github.com/Ortus-Solutions/coding-standards/blob/master/.cflintrc

Is there something I am missing?

**Comment by KamasamaK** [comment]
I've just copied this file for use myself and did not have an issue. This is using JDK8 and `CFLint-1.3.0-all.jar`.

Does it work when invoked from the command-line instead of this extension?

Can you look at the VS Code Console in Developer Tools ( Windows/Linux: Ctrl+Shift+I , macOS: Cmd+Shift+I ) and verify that the command-line string looks fine?

Even though it worked for me, I would still advise removing `output` and `inheritPlugins` since they are deprecated.

**Comment by lmajano** [comment]
This is the error I am getting @KamasamaK 
<img width="783" alt="screen shot 2018-02-12 at 3 36 23 pm" src="https://user-images.githubusercontent.com/137111/36125831-88038f22-100a-11e8-9c39-60df8e13b317.png">

Since my files are utf-8 I am thinking maybe this is a BOM issue in your extension

**Comment by KamasamaK** [comment]
This error appears to be unrelated to the `.cflintrc` file. This is a JSON parse error on the results returned by CFLint. Are you sure you are using CFLint v1.3.0? There was [an issue](https://github.com/KamasamaK/vscode-cflint/blob/master/README.md#known-issueslimitations) with the JSON output in v1.2.2 and v1.2.3 that was resolved with v1.3.0. Your screenshot cuts off the command-line string, which is what I was looking for.

**Comment by lmajano** [comment]
Ok, I see the issue then, I am using the 1.22 jar from the cflint commandbox Command
